model:
  base_learning_rate: 1.0e-04
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    identity: False
    parameterization: x0
    linear_start: 0.0015
    linear_end: 0.0205
    log_every_t: 100
    timesteps: 1000
    loss_type: l2
    first_stage_key: singingvoice
    cond_stage_key: features
    image_size: [200,10]  #change from a number into a list
    channels: 3 #euqal to the number of z_channels
    concat_mode: False #using cross attention
    monitor: val/loss
    scheduler_config:
      target: ldm.lr_scheduler.LambdaWarmUpCosineScheduler
      params:
        verbosity_interval: 0
        warm_up_steps: 1000
        max_decay_steps: 50000
        lr_start: 0.0001
        lr_max: 0.1
        lr_min: 0.0000001
    unet_config:  #改成transformer的
      target: ldm.modules.diffusionmodules.openaimodel.TransformerModel
      params:
        in_channels: 30 #the dimension of the latent space (from 40 to 10 * 3 the number of z_channels)
        out_channels: 30
        num_blocks: 3
        emb_channels: 256 #the dimension of the embedding space
        dropout: 0.1
        dims: 1
        num_heads: 8
        use_new_attention_order: True
        z_channels: 3
        use_transformer_encoder: True
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        monitor: val/rec_loss
        ckpt_path: "pretrain/first_stage/vq-f4/last.ckpt" #the path of the first stage model
        ddconfig:
          attn_type: none
          double_z: false
          z_channels: 3
          resolution: 40 #no used
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_first_stage__


data:
  target: main.DataModuleFromConfig
  params:
      batch_size: 32
      wrap: False
      num_workers: 0
      train:
          target: ldm.data.singvoice.SingVoice
          params:
              data_path: /mntnfs/med_data5/yiwenhu/diffsvc/Singing-Voice-Conversion-BingliangLi/preprocess/
              dataset_type: train
              dataset: Opencpop
      validation:
          target: ldm.data.singvoice.SingVoice
          params:
              data_path: /mntnfs/med_data5/yiwenhu/diffsvc/Singing-Voice-Conversion-BingliangLi/preprocess/
              dataset_type: test
              dataset: Opencpop

lightning:
  trainer:
    max_epochs: 300
    num_nodes: 1
    accelerator: 'gpu'
    gpus: "0"
